######################################################################
#
# File name : cpu_tb_simulate.do
# Created on: Wed Aug 12 17:20:43 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L dist_mem_gen_v8_0_10 -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.cpu_tb xil_defaultlib.glbl

do {cpu_tb_wave.do}

view wave
view structure
view signals

do {cpu_tb.udo}

run 1000ns
